method: cilqr_planner # lattice / em _planner
# method: em_planner, lattice_planner, cilqr_planner

cilqr_planner: {
  delta_t: 0.1,
  horizon: 50,
  num_state: 4,
  num_control: 2,
  w_acc: 0.5,
  w_yaw_rate: 0.5,
  w_pos_s: 0.5,
  w_pos_l: 2.0,
  w_vel: 0.5,
  q1_acc: 1.0,
  q2_acc: 1.0,
  q1_yaw_rate: 1.0,
  q2_yaw_rate: 1.0,
  q1_front: 2.75,
  q2_front: 2.75,
  q1_rear: 2.5,
  q2_rear: 2.5,
  acc_min: -5.0,
  acc_max: 5.0,
  steer_min: -1.0,
  steer_max: 1.0,
  wheel_base: 2.94,
  max_speed: 8,
  t_safe: 0.1,
  s_safe_length: 1,
  s_safe_width: 1,
  car_length: 1,
  car_width: 1,
  ego_rad: 2,
  ego_lf: 1.47, 
  ego_lr: 1.47,
  max_iters: 100,
  tol: 0.01,
  desired_speed: 5
}

lattice_planner: {
  sample_max_time: 4.0,
  sample_min_time: 2.0,
  sample_time_step: 0.5,
  sample_lat_width: 4.75,      # 3.75
  sample_width_length: 0.25,

  weight_st_object: 10.0,    # 10.0
  weight_st_jerk: 5.0,       # 5.0
  weight_lt_offset: 100.0,   # 100.0
  weight_lt_acc: 5.0        # 5.0
}

em_planner: {
  #DP Path cost
  dp_sample_l: 0.5, # dp采样横向距离间隔
  dp_sample_s: 2.5, # dp采样纵向距离间隔
  dp_sample_rows: 9, # dp采样行数（横向）
  dp_sample_cols: 10,  # dp采样列数（纵向）

  dp_cost_collision: 1.0e+9, 
  dp_cost_dl: 50.0,    # 150.0
  dp_cost_ddl: 5.0,    # 10.0
  dp_cost_dddl: 1.0,    # 1.0
  dp_cost_ref: 10.0,    # 50.0

  #QP Path cost
  qp_cost_l: 15.0,       # 15.0
  qp_cost_dl: 5.0,     # 150.0
  qp_cost_ddl: 10.0,     # 10.0
  qp_cost_dddl: 1.0,     # 1.0
  qp_cost_ref: 10.0,     # 15.0
  qp_cost_end_l: 0.0,
  qp_cost_end_dl: 0.0,
  qp_cost_end_ddl: 0.0
  
#########速度规划相关############
#TO- DO
}